/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authorize
         * @description Returns authorization cookie for credentials
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credentials pair */
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default student@g.nsu.ru */
                        email?: string;
                        /**
                         * @default internal
                         * @enum {string}
                         */
                        method?: "internal";
                        /** @default mypassword123 */
                        password?: string;
                    };
                };
            };
            responses: {
                /**
                 * @description By default, means successful authorization without responsse body.
                 *     If authorization failed, will response 200 too, see response body.
                 */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default false */
                            success: boolean;
                            /** @default Email or password is incorrect. */
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/olympiads/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of olympiads
         * @description Returns list of available olympiads for student
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful fetch */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            registeredTo?: (components["schemas"]["Olympiad"] & {
                                /** @default true */
                                frozen: boolean;
                            })[];
                            canRegisterTo?: (components["schemas"]["Olympiad"] & {
                                /** @default false */
                                hasInvite: boolean;
                            })[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get list of olympiad's tours
         * @description Returns list of available olympiad's tours for student
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful fetch */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tours?: {
                                /** @default 11388 */
                                id: string;
                                /** @default 1 */
                                isOpened: string;
                                /** @default 11376 */
                                position: string;
                                /** @default Вводный тур */
                                title: string;
                                /** @default 1 */
                                tourModel: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/common/system_data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns current server-side state. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                            olympiad?: {
                                /** @default 52 */
                                id: number;
                                /** @default Питон для детей */
                                title: string;
                                /** @default 0 */
                                teams_allowed: string;
                                /** @default 0 */
                                invitations_allowed: string;
                                /** @default 300 */
                                team: number;
                                /** @default Dream Team */
                                teamTitle: string;
                            };
                            tour?: {
                                /** @default 14641 */
                                id: number;
                                /** @default Набор задач 0 */
                                title: string;
                                /** @default 1 */
                                modelCode: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tours/enter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Save current selected tour in server-side state. */
        get: {
            parameters: {
                query?: {
                    tour?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/olympiads/enter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Save current selected olympiads in server-side state. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credentials pair */
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default 196 */
                        olympiad?: string;
                    };
                };
            };
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/common/hint_data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns info about invitations and notifications. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @default 0 */
                            usersCount: string;
                            news?: {
                                posts?: unknown[];
                            };
                            invitations?: {
                                invitations?: unknown[];
                            };
                            notifications?: unknown[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default 1337 */
                        tour: number;
                        /** @default 172800 */
                        timestamp: number;
                        notifications?: unknown[];
                    };
                };
            };
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/page_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns service info about tour and tasks of this tour. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "applications/json": {
                            /** @default Набор задач 0 */
                            tourTitle: string;
                            /** @default  */
                            infoText: string;
                            /** @default 1 */
                            tourModel: string;
                            /** @default 19.04.2025 00:00:00 */
                            startDate: string;
                            /** @default null */
                            freezeDate: string;
                            /** @default null */
                            endDate: string;
                            /** @default 1 */
                            opened: string;
                            /** @default 2 */
                            statementsShowMode: string;
                            /** @default 268241 */
                            elapsedTime: string;
                            statements: {
                                forTour: {
                                    /** @default 2575 */
                                    id: string;
                                    /** @default Условия задач */
                                    text: string;
                                };
                                forTasks: unknown[];
                            };
                            news?: unknown[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/tour_statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description PDF-file with statements for tasks of current tour. */
        get: {
            parameters: {
                query?: {
                    id?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submit/submit_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns available compilers, tasks and count of remaining tryings. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "applications/json": {
                            /** @default -29083260 */
                            tourTime: number;
                            /** @default 268452 */
                            elapsedTime: number;
                            /** @default 1 */
                            isEnabled: number;
                            /** @default 0 */
                            queueModel: number;
                            /** @default 1 */
                            isInfinite: number;
                            langs: {
                                /** @default mingw8.1c */
                                id: string;
                                /** @default MinGW64 C 8.1 */
                                title: string;
                            }[];
                            tasks: {
                                /** @default 119370 */
                                id: string;
                                /** @default 2. Время в Калифорнии */
                                title: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submit/do_submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send solution text. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** @default mingw8.1c */
                        langId?: string;
                        /** @default 119370 */
                        taskId?: string;
                        /** @default  */
                        sourceText?: string | null;
                        /** Format: binary */
                        sourceFile?: string | null;
                    };
                };
            };
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/report/get_report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Getting report of all solutions. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "applications/json": {
                            /** @default 1 */
                            display_time_and_memory: string;
                            /** @default 1 */
                            model_code: number;
                            submits?: {
                                /** @default MinGW64 C 8.1 */
                                compiler: string;
                                /** @default 2025-04-28 23:51:56 */
                                date: string;
                                /** @default 681895 */
                                id: string;
                                points?: string;
                                /** @default AAAAW */
                                result_line: string;
                                /** @default 4 */
                                status: string;
                                /** @default ICPC */
                                taskModel: string;
                                /** @default 119370 */
                                task_id: string;
                                /** @default 2. Время в Калифорнии */
                                task_title: string;
                                testNumber?: string;
                                /** @default {"1":{"t":0,"m":0}} */
                                time_and_memory: Record<string, never>;
                                total?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Logging out of NSUTS */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Olympiad: {
            /** @default 42 */
            id: string;
            /** @default Программирование */
            title: string;
            /** @default 80 */
            teams: string;
            /** @default 20 */
            tours: string;
            /** @default /nsuts-new/nsuts_img/covers/training.png */
            cover_url: string;
        };
        User: {
            /** @default 1337 */
            id: number;
            /** @default student@g.nsu.ru */
            email: string;
            /** @default Иванов */
            surname: string;
            /** @default Иван */
            name: string;
            /** @default Иванович */
            patronymic: string;
            permissions: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
